version: "3.8"

services:
  easyocr-bukti-setor:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - UPLOAD_FOLDER=uploads
      - FRONTEND_URL=http://localhost:3000
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
