services:
  # EasyOCR Web Service
  web:
    # Build using Dockerfile.minimal (yang proven work)
    build:
      context: .
      dockerfile: Dockerfile.minimal

    # Map port 8000 (sesuai dengan setup Railway)
    ports:
      - "8000:8000"

    # Load environment variables
    env_file:
      - .env

    # Restart policy
    restart: unless-stopped

    # Environment variables untuk testing
    environment:
      - PORT=8000
      - FLASK_ENV=production
