[start]
cmd = "python simple_app.py"

[phases.setup]
nixPkgs = ["python39"]

[phases.install]
cmds = ["pip install -r requirements-simple.txt"]

[variables]
PYTHONPATH = "/app"
FLASK_ENV = "production"
