# Railway configuration for Production OCR
[build]
builder = "NIXPACKS"

[build.env]
NIXPACKS_INSTALL_CMD = "apt-get update && apt-get install -y tesseract-ocr tesseract-ocr-ind libgl1-mesa-glx poppler-utils && apt-get clean && rm -rf /var/lib/apt/lists/*"

[deploy]
restartPolicyType = "ON_FAILURE" 
restartPolicyMaxRetries = 3

[variables]
FLASK_ENV = "production"
OPENCV_IO_ENABLE_OPENEXR = "0"
QT_QPA_PLATFORM = "offscreen"
